branch-defaults:
  main:
    environment: izun-production
    group_suffix: null
global:
  application_name: izun
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: il-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
